// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cards.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countCardsByNotebook = `-- name: CountCardsByNotebook :one
SELECT count(*) FROM app.cards
WHERE user_id = $1 AND notebook_id = $2
  AND ($3::app.card_state IS NULL OR state = $3)
  AND suspended_at IS NULL AND buried_until IS NULL
`

type CountCardsByNotebookParams struct {
	UserID     uuid.UUID        `json:"user_id"`
	NotebookID uuid.UUID        `json:"notebook_id"`
	State      NullAppCardState `json:"state"`
}

func (q *Queries) CountCardsByNotebook(ctx context.Context, arg CountCardsByNotebookParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCardsByNotebook, arg.UserID, arg.NotebookID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO app.cards (user_id, notebook_id, fact_id, element_id)
VALUES ($1, $2, $3, $4)
RETURNING user_id, id, notebook_id, fact_id, element_id, state, stability, difficulty, step, due, last_review, elapsed_days, scheduled_days, reps, lapses, suspended_at, buried_until, created_at, updated_at
`

type CreateCardParams struct {
	UserID     uuid.UUID `json:"user_id"`
	NotebookID uuid.UUID `json:"notebook_id"`
	FactID     uuid.UUID `json:"fact_id"`
	ElementID  string    `json:"element_id"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.UserID,
		arg.NotebookID,
		arg.FactID,
		arg.ElementID,
	)
	var i Card
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.NotebookID,
		&i.FactID,
		&i.ElementID,
		&i.State,
		&i.Stability,
		&i.Difficulty,
		&i.Step,
		&i.Due,
		&i.LastReview,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.Reps,
		&i.Lapses,
		&i.SuspendedAt,
		&i.BuriedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCardsByFactAndElements = `-- name: DeleteCardsByFactAndElements :exec
DELETE FROM app.cards
WHERE user_id = $1 AND fact_id = $2 AND element_id = ANY($3::text[])
`

type DeleteCardsByFactAndElementsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	FactID     uuid.UUID `json:"fact_id"`
	ElementIds []string  `json:"element_ids"`
}

func (q *Queries) DeleteCardsByFactAndElements(ctx context.Context, arg DeleteCardsByFactAndElementsParams) error {
	_, err := q.db.Exec(ctx, deleteCardsByFactAndElements, arg.UserID, arg.FactID, arg.ElementIds)
	return err
}

const getCard = `-- name: GetCard :one
SELECT user_id, id, notebook_id, fact_id, element_id, state, stability, difficulty, step, due, last_review, elapsed_days, scheduled_days, reps, lapses, suspended_at, buried_until, created_at, updated_at FROM app.cards
WHERE user_id = $1 AND id = $2 AND notebook_id = $3
`

type GetCardParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ID         uuid.UUID `json:"id"`
	NotebookID uuid.UUID `json:"notebook_id"`
}

func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, arg.UserID, arg.ID, arg.NotebookID)
	var i Card
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.NotebookID,
		&i.FactID,
		&i.ElementID,
		&i.State,
		&i.Stability,
		&i.Difficulty,
		&i.Step,
		&i.Due,
		&i.LastReview,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.Reps,
		&i.Lapses,
		&i.SuspendedAt,
		&i.BuriedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByFact = `-- name: ListCardsByFact :many
SELECT user_id, id, notebook_id, fact_id, element_id, state, stability, difficulty, step, due, last_review, elapsed_days, scheduled_days, reps, lapses, suspended_at, buried_until, created_at, updated_at FROM app.cards
WHERE user_id = $1 AND fact_id = $2
ORDER BY element_id ASC
`

type ListCardsByFactParams struct {
	UserID uuid.UUID `json:"user_id"`
	FactID uuid.UUID `json:"fact_id"`
}

func (q *Queries) ListCardsByFact(ctx context.Context, arg ListCardsByFactParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCardsByFact, arg.UserID, arg.FactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.NotebookID,
			&i.FactID,
			&i.ElementID,
			&i.State,
			&i.Stability,
			&i.Difficulty,
			&i.Step,
			&i.Due,
			&i.LastReview,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.Reps,
			&i.Lapses,
			&i.SuspendedAt,
			&i.BuriedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByNotebook = `-- name: ListCardsByNotebook :many
SELECT user_id, id, notebook_id, fact_id, element_id, state, stability, difficulty, step, due, last_review, elapsed_days, scheduled_days, reps, lapses, suspended_at, buried_until, created_at, updated_at FROM app.cards
WHERE user_id = $1 AND notebook_id = $2
  AND ($3::app.card_state IS NULL OR state = $3)
  AND suspended_at IS NULL AND buried_until IS NULL
ORDER BY due ASC NULLS FIRST, created_at ASC
LIMIT $5 OFFSET $4
`

type ListCardsByNotebookParams struct {
	UserID     uuid.UUID        `json:"user_id"`
	NotebookID uuid.UUID        `json:"notebook_id"`
	State      NullAppCardState `json:"state"`
	RowOffset  int32            `json:"row_offset"`
	RowLimit   int32            `json:"row_limit"`
}

func (q *Queries) ListCardsByNotebook(ctx context.Context, arg ListCardsByNotebookParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCardsByNotebook,
		arg.UserID,
		arg.NotebookID,
		arg.State,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.NotebookID,
			&i.FactID,
			&i.ElementID,
			&i.State,
			&i.Stability,
			&i.Difficulty,
			&i.Step,
			&i.Due,
			&i.LastReview,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.Reps,
			&i.Lapses,
			&i.SuspendedAt,
			&i.BuriedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
