// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAuthProvider string

const (
	AppAuthProviderPassword AppAuthProvider = "password"
	AppAuthProviderGoogle   AppAuthProvider = "google"
	AppAuthProviderApple    AppAuthProvider = "apple"
)

func (e *AppAuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppAuthProvider(s)
	case string:
		*e = AppAuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AppAuthProvider: %T", src)
	}
	return nil
}

type NullAppAuthProvider struct {
	AppAuthProvider AppAuthProvider `json:"app_auth_provider"`
	Valid           bool            `json:"valid"` // Valid is true if AppAuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AppAuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppAuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppAuthProvider), nil
}

type AppCardState string

const (
	AppCardStateNew        AppCardState = "new"
	AppCardStateLearning   AppCardState = "learning"
	AppCardStateReview     AppCardState = "review"
	AppCardStateRelearning AppCardState = "relearning"
)

func (e *AppCardState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppCardState(s)
	case string:
		*e = AppCardState(s)
	default:
		return fmt.Errorf("unsupported scan type for AppCardState: %T", src)
	}
	return nil
}

type NullAppCardState struct {
	AppCardState AppCardState `json:"app_card_state"`
	Valid        bool         `json:"valid"` // Valid is true if AppCardState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppCardState) Scan(value interface{}) error {
	if value == nil {
		ns.AppCardState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppCardState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppCardState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppCardState), nil
}

type AppRating string

const (
	AppRatingAgain AppRating = "again"
	AppRatingHard  AppRating = "hard"
	AppRatingGood  AppRating = "good"
	AppRatingEasy  AppRating = "easy"
)

func (e *AppRating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppRating(s)
	case string:
		*e = AppRating(s)
	default:
		return fmt.Errorf("unsupported scan type for AppRating: %T", src)
	}
	return nil
}

type NullAppRating struct {
	AppRating AppRating `json:"app_rating"`
	Valid     bool      `json:"valid"` // Valid is true if AppRating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppRating) Scan(value interface{}) error {
	if value == nil {
		ns.AppRating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppRating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppRating), nil
}

type AppFact struct {
	UserID     uuid.UUID   `json:"user_id"`
	ID         uuid.UUID   `json:"id"`
	NotebookID uuid.UUID   `json:"notebook_id"`
	FactType   string      `json:"fact_type"`
	Content    []byte      `json:"content"`
	SourceID   pgtype.UUID `json:"source_id"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type AppReview struct {
	UserID           uuid.UUID     `json:"user_id"`
	ID               uuid.UUID     `json:"id"`
	CardID           pgtype.UUID   `json:"card_id"`
	NotebookID       uuid.UUID     `json:"notebook_id"`
	FactID           pgtype.UUID   `json:"fact_id"`
	ElementID        pgtype.Text   `json:"element_id"`
	ReviewedAt       time.Time     `json:"reviewed_at"`
	Rating           AppRating     `json:"rating"`
	ReviewDurationMs pgtype.Int4   `json:"review_duration_ms"`
	Mode             string        `json:"mode"`
	StateBefore      AppCardState  `json:"state_before"`
	StabilityBefore  pgtype.Float4 `json:"stability_before"`
	DifficultyBefore pgtype.Float4 `json:"difficulty_before"`
	ElapsedDays      float32       `json:"elapsed_days"`
	ScheduledDays    float32       `json:"scheduled_days"`
	StateAfter       AppCardState  `json:"state_after"`
	StabilityAfter   float32       `json:"stability_after"`
	DifficultyAfter  float32       `json:"difficulty_after"`
	IntervalDays     float32       `json:"interval_days"`
	Retrievability   pgtype.Float4 `json:"retrievability"`
	CreatedAt        time.Time     `json:"created_at"`
}

type AuthIdentity struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        AppAuthProvider    `json:"provider"`
	ProviderUserID  string             `json:"provider_user_id"`
	Email           pgtype.Text        `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type Card struct {
	UserID        uuid.UUID          `json:"user_id"`
	ID            uuid.UUID          `json:"id"`
	NotebookID    uuid.UUID          `json:"notebook_id"`
	FactID        uuid.UUID          `json:"fact_id"`
	ElementID     string             `json:"element_id"`
	State         AppCardState       `json:"state"`
	Stability     pgtype.Float4      `json:"stability"`
	Difficulty    pgtype.Float4      `json:"difficulty"`
	Step          pgtype.Int2        `json:"step"`
	Due           pgtype.Timestamptz `json:"due"`
	LastReview    pgtype.Timestamptz `json:"last_review"`
	ElapsedDays   float32            `json:"elapsed_days"`
	ScheduledDays float32            `json:"scheduled_days"`
	Reps          int32              `json:"reps"`
	Lapses        int32              `json:"lapses"`
	SuspendedAt   pgtype.Timestamptz `json:"suspended_at"`
	BuriedUntil   pgtype.Date        `json:"buried_until"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type Notebook struct {
	UserID       uuid.UUID          `json:"user_id"`
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Emoji        pgtype.Text        `json:"emoji"`
	Color        pgtype.Text        `json:"color"`
	Position     int32              `json:"position"`
	TotalCards   int32              `json:"total_cards"`
	FsrsSettings []byte             `json:"fsrs_settings"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	Username        string             `json:"username"`
	DisplayName     pgtype.Text        `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Locale          pgtype.Text        `json:"locale"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserSession struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TokenHash  []byte      `json:"token_hash"`
	UserAgent  pgtype.Text `json:"user_agent"`
	IpAddress  *netip.Addr `json:"ip_address"`
	ExpiresAt  time.Time   `json:"expires_at"`
	CreatedAt  time.Time   `json:"created_at"`
	LastUsedAt time.Time   `json:"last_used_at"`
}
