// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAuthProvider string

const (
	AppAuthProviderPassword AppAuthProvider = "password"
	AppAuthProviderGoogle   AppAuthProvider = "google"
	AppAuthProviderApple    AppAuthProvider = "apple"
)

func (e *AppAuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppAuthProvider(s)
	case string:
		*e = AppAuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AppAuthProvider: %T", src)
	}
	return nil
}

type NullAppAuthProvider struct {
	AppAuthProvider AppAuthProvider `json:"app_auth_provider"`
	Valid           bool            `json:"valid"` // Valid is true if AppAuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AppAuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppAuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppAuthProvider), nil
}

type AuthIdentity struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        AppAuthProvider    `json:"provider"`
	ProviderUserID  string             `json:"provider_user_id"`
	Email           pgtype.Text        `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type Notebook struct {
	UserID       uuid.UUID          `json:"user_id"`
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	FsrsSettings []byte             `json:"fsrs_settings"`
	Position     int32              `json:"position"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	Username        string             `json:"username"`
	DisplayName     pgtype.Text        `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Locale          pgtype.Text        `json:"locale"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserSession struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TokenHash  []byte      `json:"token_hash"`
	UserAgent  pgtype.Text `json:"user_agent"`
	IpAddress  *netip.Addr `json:"ip_address"`
	ExpiresAt  time.Time   `json:"expires_at"`
	CreatedAt  time.Time   `json:"created_at"`
	LastUsedAt time.Time   `json:"last_used_at"`
}
