// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveNotebook(ctx context.Context, arg ArchiveNotebookParams) (int64, error)
	CountCardsByNotebook(ctx context.Context, arg CountCardsByNotebookParams) (int64, error)
	CountFactsByNotebook(ctx context.Context, arg CountFactsByNotebookParams) (int64, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateFact(ctx context.Context, arg CreateFactParams) (AppFact, error)
	// Note: fsrs_settings is always provided from Go code (source of truth for defaults)
	CreateNotebook(ctx context.Context, arg CreateNotebookParams) (Notebook, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Creates a user and their password auth identity in a single transaction-friendly call
	CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (CreateUserWithPasswordRow, error)
	DeleteCardsByFactAndElements(ctx context.Context, arg DeleteCardsByFactAndElementsParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteFact(ctx context.Context, arg DeleteFactParams) (int64, error)
	DeleteSession(ctx context.Context, tokenHash []byte) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	GetAuthIdentityByEmail(ctx context.Context, email pgtype.Text) (GetAuthIdentityByEmailRow, error)
	GetAuthIdentityByProviderID(ctx context.Context, arg GetAuthIdentityByProviderIDParams) (GetAuthIdentityByProviderIDRow, error)
	GetCard(ctx context.Context, arg GetCardParams) (Card, error)
	GetFact(ctx context.Context, arg GetFactParams) (GetFactRow, error)
	GetNotebook(ctx context.Context, arg GetNotebookParams) (Notebook, error)
	GetSessionByToken(ctx context.Context, tokenHash []byte) (GetSessionByTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Get user with password hash for authentication
	GetUserByEmailPassword(ctx context.Context, email pgtype.Text) (GetUserByEmailPasswordRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Returns whether a notebook exists and its archived status.
	// Used for idempotent archive operations.
	IsNotebookArchived(ctx context.Context, arg IsNotebookArchivedParams) (IsNotebookArchivedRow, error)
	ListCardsByFact(ctx context.Context, arg ListCardsByFactParams) ([]Card, error)
	ListCardsByNotebook(ctx context.Context, arg ListCardsByNotebookParams) ([]Card, error)
	ListFactsByNotebook(ctx context.Context, arg ListFactsByNotebookParams) ([]ListFactsByNotebookRow, error)
	ListNotebooks(ctx context.Context, userID uuid.UUID) ([]Notebook, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UnarchiveNotebook(ctx context.Context, arg UnarchiveNotebookParams) error
	UpdateFactContent(ctx context.Context, arg UpdateFactContentParams) (AppFact, error)
	UpdateNotebook(ctx context.Context, arg UpdateNotebookParams) (Notebook, error)
	UpdateSessionLastUsed(ctx context.Context, tokenHash []byte) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
