// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO app.user_sessions (user_id, token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, user_agent, ip_address, expires_at, created_at, last_used_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash []byte      `json:"token_hash"`
	UserAgent pgtype.Text `json:"user_agent"`
	IpAddress *netip.Addr `json:"ip_address"`
	ExpiresAt time.Time   `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM app.user_sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM app.user_sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM app.user_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.user_id, s.token_hash, s.user_agent, s.ip_address, s.expires_at, s.created_at, s.last_used_at, u.email, u.username
FROM app.user_sessions s
JOIN app.users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
  AND u.deleted_at IS NULL
`

type GetSessionByTokenRow struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TokenHash  []byte      `json:"token_hash"`
	UserAgent  pgtype.Text `json:"user_agent"`
	IpAddress  *netip.Addr `json:"ip_address"`
	ExpiresAt  time.Time   `json:"expires_at"`
	CreatedAt  time.Time   `json:"created_at"`
	LastUsedAt time.Time   `json:"last_used_at"`
	Email      string      `json:"email"`
	Username   string      `json:"username"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, tokenHash []byte) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, tokenHash)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE app.user_sessions
SET last_used_at = now()
WHERE token_hash = $1
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, updateSessionLastUsed, tokenHash)
	return err
}
