// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO app.auth_identities (user_id, provider, provider_user_id, email, password_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, provider_user_id, email, email_verified_at, password_hash, created_at, updated_at
`

type CreateAuthIdentityParams struct {
	UserID         uuid.UUID       `json:"user_id"`
	Provider       AppAuthProvider `json:"provider"`
	ProviderUserID string          `json:"provider_user_id"`
	Email          pgtype.Text     `json:"email"`
	PasswordHash   pgtype.Text     `json:"password_hash"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.PasswordHash,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app.users (email, username, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, email_verified_at, username, display_name, avatar_url, locale, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email       string      `json:"email"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUserWithPassword = `-- name: CreateUserWithPassword :one
WITH new_user AS (
    INSERT INTO app.users (email, username, display_name)
    VALUES ($1, $3, $4)
    RETURNING id, email, email_verified_at, username, display_name, avatar_url, locale, created_at, updated_at, deleted_at
)
INSERT INTO app.auth_identities (user_id, provider, provider_user_id, email, password_hash)
SELECT id, 'password', id::text, $1, $2
FROM new_user
RETURNING (SELECT id FROM new_user), (SELECT email FROM new_user), (SELECT username FROM new_user)
`

type CreateUserWithPasswordParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Username     string      `json:"username"`
	DisplayName  pgtype.Text `json:"display_name"`
}

type CreateUserWithPasswordRow struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Username string    `json:"username"`
}

// Creates a user and their password auth identity in a single transaction-friendly call
func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (CreateUserWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.DisplayName,
	)
	var i CreateUserWithPasswordRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const getAuthIdentityByEmail = `-- name: GetAuthIdentityByEmail :one
SELECT ai.id, ai.user_id, ai.provider, ai.provider_user_id, ai.email, ai.email_verified_at, ai.password_hash, ai.created_at, ai.updated_at, u.email as "user_email", u.username as "user_username"
FROM app.auth_identities ai
JOIN app.users u ON u.id = ai.user_id
WHERE ai.provider = 'password'
  AND ai.email = $1
  AND u.deleted_at IS NULL
`

type GetAuthIdentityByEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        AppAuthProvider    `json:"provider"`
	ProviderUserID  string             `json:"provider_user_id"`
	Email           pgtype.Text        `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	UserEmail       string             `json:"user_email"`
	UserUsername    string             `json:"user_username"`
}

func (q *Queries) GetAuthIdentityByEmail(ctx context.Context, email pgtype.Text) (GetAuthIdentityByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByEmail, email)
	var i GetAuthIdentityByEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserEmail,
		&i.UserUsername,
	)
	return i, err
}

const getAuthIdentityByProviderID = `-- name: GetAuthIdentityByProviderID :one
SELECT ai.id, ai.user_id, ai.provider, ai.provider_user_id, ai.email, ai.email_verified_at, ai.password_hash, ai.created_at, ai.updated_at, u.email as "user_email", u.username as "user_username"
FROM app.auth_identities ai
JOIN app.users u ON u.id = ai.user_id
WHERE ai.provider = $1
  AND ai.provider_user_id = $2
  AND u.deleted_at IS NULL
`

type GetAuthIdentityByProviderIDParams struct {
	Provider       AppAuthProvider `json:"provider"`
	ProviderUserID string          `json:"provider_user_id"`
}

type GetAuthIdentityByProviderIDRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        AppAuthProvider    `json:"provider"`
	ProviderUserID  string             `json:"provider_user_id"`
	Email           pgtype.Text        `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	UserEmail       string             `json:"user_email"`
	UserUsername    string             `json:"user_username"`
}

func (q *Queries) GetAuthIdentityByProviderID(ctx context.Context, arg GetAuthIdentityByProviderIDParams) (GetAuthIdentityByProviderIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByProviderID, arg.Provider, arg.ProviderUserID)
	var i GetAuthIdentityByProviderIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserEmail,
		&i.UserUsername,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, username, display_name, avatar_url, locale, created_at, updated_at, deleted_at FROM app.users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmailPassword = `-- name: GetUserByEmailPassword :one
SELECT u.id, u.email, u.username, ai.password_hash
FROM app.users u
JOIN app.auth_identities ai ON ai.user_id = u.id
WHERE ai.provider = 'password'
  AND ai.email = $1
  AND u.deleted_at IS NULL
`

type GetUserByEmailPasswordRow struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

// Get user with password hash for authentication
func (q *Queries) GetUserByEmailPassword(ctx context.Context, email pgtype.Text) (GetUserByEmailPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailPassword, email)
	var i GetUserByEmailPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, username, display_name, avatar_url, locale, created_at, updated_at, deleted_at FROM app.users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, email_verified_at, username, display_name, avatar_url, locale, created_at, updated_at, deleted_at FROM app.users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE app.users
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE app.users
SET display_name = COALESCE($2, display_name),
    avatar_url = COALESCE($3, avatar_url),
    locale = COALESCE($4, locale)
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, email_verified_at, username, display_name, avatar_url, locale, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Locale      pgtype.Text `json:"locale"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
